replicaCount: 1
deployment:
  image: quay.io/go-skynet/local-ai:latest
  env:
    context_size: 1024
  modelsPath: /models
forceDownload: false
service:
  type: ClusterIP
  port: 80
  metadata: null
  namespace: default
  annotations: {}
ingress:
  enabled: true
  className: alb
  metadata:
    name: alb-ingress
    namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012
    alb.ingress.kubernetes.io/ssl-redirect: '443'
  labels:
    app: alb-ingress
  hosts:
  - host: api.example.com
  service:
    port: 80
nodeSelector: {}
tolerations: []
affinity: {}
persistence:
  pvc:
    enabled: true
    size: 5Gi
    accessModes:
    - ReadWriteMany
    annotations: {}
    volumeHandle: fs-1234567890
    storageClass: null
  hostPath:
    enabled: false
    path: /models
models:
- name: luna-ai-llama2-uncensored-q4-k-m
  url: https://huggingface.co/TheBloke/Luna-AI-Llama2-Uncensored-GGUF/resolve/main/luna-ai-llama2-uncensored.Q4_K_M.gguf
  threads: 16
  replicaCount: 1
  resources:
    limits:
      cpu: 16384m
      memory: 32768Mi
      ephemeral-storage: 166Gi
    requests:
      cpu: 8192m
      memory: 16384Mi
      ephemeral-storage: 83Gi
  promptTemplate:
    luna-ai-llama2-uncensored.Q4_K_M.tmpl: 'You are a helpful AI assistant.

      USER: {{.Input}}

      ASSISTANT:'
