{{- if .Values.models }}
{{- if gt (len .Values.models) 0 }}
{{- $root := . }}
{{- range .Values.models }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "local-ai.fullname" $root }}-{{ include "local-ai.sanitizeName" .name }}
  namespace: {{ $root.Release.Namespace | quote }}
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "local-ai.fullname" $root }}-{{ include "local-ai.sanitizeName" .name }}
  targetCPUUtilizationPercentage: 50
---
{{- end }}
{{- end }}
{{- end }}
